[package]
name = "plotly"
version = "0.8.0"
description = "A plotting library powered by Plotly.js"
authors = ["Ioannis Giagkiozis <i.giagkiozis@gmail.com>"]
license = "MIT"
workspace = ".."
readme = "README.md"
homepage = "https://github.com/igiagkiozis/plotly"
documentation = "https://docs.rs/plotly"
repository = "https://github.com/igiagkiozis/plotly"
edition = "2018"
keywords = ["plot", "chart", "plotly"]

exclude = ["target/*"]

[features]
# Adds plot save functionality to the following formats: png, jpeg, webp, svg, pdf and eps.
kaleido = ["plotly_kaleido"]
plotly_ndarray = ["ndarray"]
wasm = ["getrandom", "js-sys", "wasm-bindgen", "wasm-bindgen-futures"]

[dependencies]
askama = { version = "0.11.0", features = ["serde-json"] }
dyn-clone = "1"
erased-serde = "0.3"
getrandom = { version = "0.2", features = ["js"], optional = true }
js-sys = { version = "0.3", optional = true }
plotly_kaleido = { version = "0.3.0", path = "../plotly_kaleido", optional = true }
ndarray = { version = "0.15.4", optional = true }
once_cell = "1"
serde = { version = "1.0.132", features = ["derive"] }
serde_json = "1.0.73"
serde_repr = "0.1"
serde_with = "2"
rand = "0.8"
rand_distr = "0.4"
wasm-bindgen = { version = "0.2", optional = true }
wasm-bindgen-futures = { version = "0.4", optional = true }

[dev-dependencies]
plotly_kaleido = { version = "0.3.0", path = "../plotly_kaleido" }
itertools = "0.10.3"
itertools-num = "0.1.3"
csv = "1.1.6"
ndarray = "0.15.4"
