[package]
name = "plotly"
version = "0.7.0"
description = "A plotting library powered by Plotly.js"
authors = ["Ioannis Giagkiozis <i.giagkiozis@gmail.com>"]
license = "MIT"
workspace = ".."
readme = "README.md"
homepage = "https://github.com/igiagkiozis/plotly"
documentation = "https://docs.rs/plotly"
repository = "https://github.com/igiagkiozis/plotly"
edition = "2018"
keywords = ["plot", "chart", "plotly"]

exclude = ["target/*"]

[features]
# Adds plot save functionality to the following formats: png, jpeg, webp, svg, pdf and eps.
kaleido = ["plotly_kaleido"]
plotly_ndarray = ["ndarray"]

[dependencies]
askama = "0.10.5"
dyn-clone = { version = "1" }
ndarray = { version = "0.15.1", optional = true }
plotly_kaleido = { version = "0.3.0", path = "../plotly_kaleido", optional = true }
rand = "0.8.3"
rand_distr = "0.4.0"
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"


[dev-dependencies]
plotly_kaleido = { version = "0.3.0", path = "../plotly_kaleido" }
itertools = "0.10.0"
itertools-num = "0.1.3"
csv = "1.1.6"
ndarray = "0.15.1"
