[package]
name = "plotly"
version = "0.4.1"
description = "A plotting library powered by Plotly.js"
authors = ["Ioannis Giagkiozis <i.giagkiozis@gmail.com>"]
license = "MIT"
workspace = ".."
readme = "README.md"
homepage = "https://github.com/igiagkiozis/plotly"
documentation = "https://docs.rs/plotly"
repository = "https://github.com/igiagkiozis/plotly"
edition = "2018"
keywords = ["plot", "chart", "plotly"]

exclude = [
    "target/*"
]

[features]
# Adds plot save functionality to the following formats: png, jpeg, webp, svg, pdf and eps.
orca = ["plotly_orca"]
ndarray_scatter = ["ndarray"]

[dependencies]
plotly_orca = { version = "0.2.1", path = "../plotly_orca", optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
askama = "0.9.0"
rand = "0.7.3"
rand_distr = "0.2.2"
num = "0.2.1"
ndarray = { version = "0.13.0", optional = true }

[dev-dependencies]
plotly_orca = { version = "0.2.1", path = "../plotly_orca" }
