[package]
name = "wasm-yew-minimal"
version = "0.1.0"
authors = ["Michael Freeborn <michaelfreeborn1@gmail.com>"]
edition = "2021"

[dependencies]
plotly = { path = "../../plotly", features = ["wasm"] }
yew = "0.19.0"
yew-hooks = "0.1.56"
log = "0.4.6"
wasm-logger = "0.2"