name: CI

on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

# Cancel any in-flight jobs for the same PR/branch so there's only one active
# at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RUST_BACKTRACE: full

jobs:
  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check
      - run: cd ${{ github.workspace }}/examples && cargo fmt --all -- --check
    
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - run: cargo clippy -- -D warnings
      - run: cd ${{ github.workspace }}/examples && cargo clippy -- -D warnings

  test:
    name: Tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --features=plotly_ndarray,kaleido
  
  code-coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview
      - uses: taiki-e/install-action@cargo-llvm-cov
      - run: cargo llvm-cov --workspace --features=plotly_ndarray,plotly_image,kaleido --lcov --output-path lcov.info
      - uses: codecov/codecov-action@v3
      
  build_examples:
    name: Build Examples
    strategy:
      fail-fast: false
      matrix:
        example: [  # missing jupyter and wasm-yew-minimal
          3d_charts,
          basic_charts,
          custom_controls,
          financial_charts,
          images,
          kaleido,
          maps,
          ndarray,
          scientific_charts,
          shapes,
          subplots
        ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cd ${{ github.workspace }}/examples/${{ matrix.example }} && cargo build

