name: build_dev

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

env:
  CARGO_TERM_COLOR: always

jobs:
  run_code_coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        run: rustup toolchain install stable --component llvm-tools-preview
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Generate code coverage
        run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          files: lcov.info
          fail_ci_if_error: true

  build_linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: build_linux
        run: cargo build --all-features --verbose --release
      - name: Run tests
        run: cargo test --all-features --release --verbose
      - name: Run basic charts
        run: cargo run --example basic_charts --all-features --release
      - name: Run financial charts
        run: cargo run --example financial_charts --all-features --release
      - name: Run fundamentals
        run: cargo run --example fundamentals --all-features --release
      - name: Run ndarray support
        run: cargo run --example ndarray_support --all-features --release
      - name: Run scientific charts
        run: cargo run --example scientific_charts --all-features --release
      - name: Run statistical charts
        run: cargo run --example statistical_charts --all-features --release
      - name: Run subplots
        run: cargo run --example subplots --all-features --release

  build_windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: build_windows
        run: cargo build --all-features --verbose --release
      - name: Run tests
        run: cargo test --all-features --release --verbose
      - name: Run basic charts
        run: cargo run --example basic_charts --all-features --release
      - name: Run financial charts
        run: cargo run --example financial_charts --all-features --release
      - name: Run fundamentals
        run: cargo run --example fundamentals --all-features --release
      - name: Run ndarray support
        run: cargo run --example ndarray_support --all-features --release
      - name: Run scientific charts
        run: cargo run --example scientific_charts --all-features --release
      - name: Run statistical charts
        run: cargo run --example statistical_charts --all-features --release
      - name: Run subplots
        run: cargo run --example subplots --all-features --release

  build_macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: build_macos
        run: cargo build --all-features --verbose --release
      - name: Run tests
        run: cargo test --all-features --release --verbose
      - name: Run basic charts
        run: cargo run --example basic_charts --all-features --release
      - name: Run financial charts
        run: cargo run --example financial_charts --all-features --release
      - name: Run fundamentals
        run: cargo run --example fundamentals --all-features --release
      - name: Run ndarray support
        run: cargo run --example ndarray_support --all-features --release
      - name: Run scientific charts
        run: cargo run --example scientific_charts --all-features --release
      - name: Run statistical charts
        run: cargo run --example statistical_charts --all-features --release
      - name: Run subplots
        run: cargo run --example subplots --all-features --release
