name: build_master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  run_code_coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Install cargo-tarpaulin
      uses: baptiste0928/cargo-install@v1
      with:
        crate: cargo-tarpaulin
    - name: Run cargo-tarpaulin
      run: cargo tarpaulin --all-features --release --debug
    - name: Upload to codecov.io
      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        
  build_linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build_linux
      run: cargo build --all-features --verbose
    - name: Run tests
      run: cargo test --all-features --release --verbose
    - name: Run basic charts
      run: cargo run --example basic_charts --all-features --release
    - name: Run financial charts
      run: cargo run --example financial_charts --all-features --release
    - name: Run fundamentals
      run: cargo run --example fundamentals --all-features --release
    - name: Run ndarray support
      run: cargo run --example ndarray_support --all-features --release
    - name: Run scientific charts
      run: cargo run --example scientific_charts --all-features --release
    - name: Run statistical charts
      run: cargo run --example statistical_charts --all-features --release
    - name: Run subplots
      run: cargo run --example subplots --all-features --release

  build_windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: build_windows
        run: cargo build --all-features --verbose
      - name: Run tests
        run: cargo test --all-features --release --verbose
      - name: Run basic charts
        run: cargo run --example basic_charts --all-features --release
      - name: Run financial charts
        run: cargo run --example financial_charts --all-features --release
      - name: Run fundamentals
        run: cargo run --example fundamentals --all-features --release
      - name: Run ndarray support
        run: cargo run --example ndarray_support --all-features --release
      - name: Run scientific charts
        run: cargo run --example scientific_charts --all-features --release
      - name: Run statistical charts
        run: cargo run --example statistical_charts --all-features --release
      - name: Run subplots
        run: cargo run --example subplots --all-features --release

  build_macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: build_macos
        run: cargo build --all-features --verbose
      - name: Run tests
        run: cargo test --all-features --release --verbose
      - name: Run basic charts
        run: cargo run --example basic_charts --all-features --release
      - name: Run financial charts
        run: cargo run --example financial_charts --all-features --release
      - name: Run fundamentals
        run: cargo run --example fundamentals --all-features --release
      - name: Run ndarray support
        run: cargo run --example ndarray_support --all-features --release
      - name: Run scientific charts
        run: cargo run --example scientific_charts --all-features --release
      - name: Run statistical charts
        run: cargo run --example statistical_charts --all-features --release
      - name: Run subplots
        run: cargo run --example subplots --all-features --release